apiVersion: v1
kind: Secret
metadata:
  name: {{ template "PLAYShop.fullname" . }}
  labels:
    app: {{ template "PLAYShop.name" . }}
    chart: {{ template "PLAYShop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.PLAYShopSecretKey | default "" | ne "" }}
  PLAYShop-secret-key: {{ .Values.PLAYShopSecretKey | b64enc | quote }}
  {{- else }}
  PLAYShop-secret-key: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end -}}
